/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "veilarbregistrering"

pluginManagement.resolutionStrategy.eachPlugin {
    when {
        requested.id.id.startsWith("org.jetbrains.kotlin.") -> useVersion("1.5.30")
        requested.id.id.startsWith("org.springframework.boot.") -> useVersion("2.3.8.RELEASE")
    }
}