spring:
  flyway:
    enabled: true
    table: schema_version
  datasource:
    url: ${VEILARBREGISTRERINGDB_URL}
    username: ${VEILARBREGISTRERINGDB_USERNAME}
    password: ${VEILARBREGISTRERINGDB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
